#!/bin/sh
# Fetch the third-party files under public/vendor and public/js/wordlist.js.
# Re-running must reproduce the committed files byte for byte; verify with
# `shasum -a 256 -c public/vendor/SHA256SUMS`.
set -eu

LIBSODIUM_VERSION=0.8.4
WORDLIST_URL=https://www.eff.org/files/2016/09/08/eff_short_wordlist_2_0.txt
WORDLIST_SHA256=22b45c52e0bd0bbf03aa522240b111eb4c7c0c1d86c4e518e1be2a7eb2a625e4

root=$(cd "$(dirname "$0")/.." && pwd)
vendor=$root/public/vendor
tmp=$(mktemp -d)
trap 'rm -rf "$tmp"' EXIT

# libsodium: npm pack checks the registry integrity hash
cd "$tmp"
npm pack --silent "libsodium-sumo@$LIBSODIUM_VERSION" "libsodium-wrappers-sumo@$LIBSODIUM_VERSION" >/dev/null
mkdir core wrappers
tar xzf "libsodium-sumo-$LIBSODIUM_VERSION.tgz" -C core
tar xzf "libsodium-wrappers-sumo-$LIBSODIUM_VERSION.tgz" -C wrappers

# Browsers cannot resolve the bare specifier; .js avoids .mjs MIME problems on Apache
cp core/package/dist/modules-sumo-esm/libsodium-sumo.mjs "$vendor/libsodium-sumo.js"
sed 's|from"libsodium-sumo"|from"./libsodium-sumo.js"|' \
    wrappers/package/dist/modules-sumo-esm/libsodium-wrappers.mjs > "$vendor/libsodium-wrappers.js"
grep -q 'from"./libsodium-sumo.js"' "$vendor/libsodium-wrappers.js"
cp core/package/LICENSE "$vendor/LICENSE.libsodium"

# EFF short wordlist 2: every word is unique in its first three letters.
# "yo-yo" becomes "yoyo" so that '-' can serve as a word separator.
curl -sSfL -o wordlist.txt "$WORDLIST_URL"
echo "$WORDLIST_SHA256  wordlist.txt" | shasum -a 256 -c - >/dev/null
{
    echo "// EFF short wordlist 2.0, https://www.eff.org/dice (CC BY 3.0 US)."
    echo "// Generated by tools/vendor.sh; \"yo-yo\" is spelled \"yoyo\"."
    echo "export const WORDLIST = Object.freeze(["
    awk '{ w = $2; gsub(/-/, "", w); printf "  \"%s\",\n", w }' wordlist.txt
    echo "]);"
} > "$root/public/js/wordlist.js"

cd "$vendor"
shasum -a 256 libsodium-sumo.js libsodium-wrappers.js > SHA256SUMS
